### Roger Waters - The Dark Side of the Moon Redux (original)
GET https://coverartarchive.org/release/a43add4a-0967-4aa0-a041-dcaf8f99a17a/back

### Roger Waters - The Dark Side of the Moon Redux (Thumbnail - 250px)
GET https://coverartarchive.org/release/a43add4a-0967-4aa0-a041-dcaf8f99a17a/back-250

### Roger Waters - The Dark Side of the Moon Redux (Thumbnail - 500px)
GET https://coverartarchive.org/release/a43add4a-0967-4aa0-a041-dcaf8f99a17a/back-500

### Roger Waters - The Dark Side of the Moon Redux (Thumbnail - 1200px)
GET https://coverartarchive.org/release/a43add4a-0967-4aa0-a041-dcaf8f99a17a/back-1200
